#!/bin/bash
#2 15
declare -a XASFiles
XASFiles=$(ls xas/)

#CO203Oct2013235037_52-CO203Oct2013235037.C1-XCH.xas.5.xas
for i in "${XASFiles[@]}"
do
	temp=$(echo $i | sed -e 's/\<.+_[0-9]+-.+\.[A-Za-z]\>0*\<[0-9]+-XCH\.xas\.5\.xas\>/\1\2/')
	echo $temp
done


CIF=$1

#LATTICE_A=grep _cell_length_a $CIF | grep -e []
#LATTICE_B=grep _cell_length_b $CIF
#LATTICE_C=grep _cell_length_c $CIF
#ALPHA=grep _cell_angle_alpha $CIF
#BETA=grep _cell_angle_beta $CIF
#GAMMA=grep _cell_angle_gamma $CIF

python main.py > distance_intensities
rm *.pyc
